import swaggerUI from "swagger-ui-express";
import swaggerJsDoc from "swagger-jsdoc";
import { Express } from "express";

const options = {
    definition: {
        openapi: "3.0.0",
        info: {
            title: "API",
            version: "1.0.0",
            description: "API with autogenerated swagger doc",
        },
        servers: [
            {
                url: "http://localhost:4000",
            },
        ],
    },
    apis: ["src/index.ts"],
};

function useSwagger(app: Express) {
    const specs = swaggerJsDoc(options);
    app.use("/docs", swaggerUI.serve, swaggerUI.setup(specs, { explorer: true }));
}

export default useSwagger;
