# This is a basic workflow to help you get started with Actions

name: Web - Deploy to firebase

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    tag: ["v*"]
    paths:
      - "web/**"

  workflow_dispatch:
  workflow_call:
    inputs:
      pull-latest:
        required: false
        type: boolean
        default: false
    secrets:
      GOLD_PRICE_SERVER_URL:
        description: "server url"
        required: true
      FIREBASE_API_KEY:
        description: "firebase api key"
        required: true
      FIREBASE_AUTH_DOMAIN:
        description: "firebase auth domain"
        required: true
      FIREBASE_DATABASE_URL:
        description: "firebase database url"
        required: true
      FIREBASE_PROJECT_ID:
        description: "firebase project id"
        required: true
      FIREBASE_STORAGE_BUCKET:
        description: "firebase storage bucket"
        required: true
      FIREBASE_MESSAGING_SENDER_ID:
        description: "firebase messaging sender id"
        required: true
      FIREBASE_APP_ID:
        description: "firebase app id"
        required: true
      FIREBASE_MEASUREMENT_ID:
        description: "firebase measurement id"
        required: true
      FIREBASE_SERVICE_ACCOUNT_GOLDPRICETRACKING:
        description: "firebase service account"
        required: true

defaults:
  run:
    working-directory: web

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-web:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Pull latest
        if: ${{ inputs.pull-latest }}
        run: git pull

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install package
        run: yarn install

      - name: build
        run: yarn build
        env:
          VITE_SERVER_URL: ${{ secrets.GOLD_PRICE_SERVER_URL }}
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GOLDPRICETRACKING }}"
          channelId: live
          projectId: goldpricetracking
          entryPoint: ./web
